# Generated by Django 3.2.19 on 2023-06-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=50)),
                ('offer_banner', models.ImageField(upload_to='bannerImage')),
                ('starting_price', models.CharField(max_length=20)),
            ],
        ),
    ]
