# Generated by Django 4.2.9 on 2024-02-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=50)),
                ('offer_banner', models.ImageField(upload_to='bannerImage')),
                ('starting_price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_pic', models.ImageField(upload_to='banner')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
