# Generated by Django 3.2.19 on 2023-06-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_pic', models.ImageField(upload_to='banner')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
