# Generated by Django 4.2.9 on 2024-03-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTraking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderTrack', models.CharField(max_length=156)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order_App.order')),
            ],
        ),
    ]
