# Generated by Django 3.2.19 on 2023-06-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_App', '0002_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_num',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
