# Generated by Django 3.2.19 on 2023-06-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_App', '0003_order_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
