# Generated by Django 4.1.7 on 2023-03-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Factory', 'Factory'), ('Customer', 'Customer')], default='Customer', max_length=20),
        ),
    ]
