# Generated by Django 3.2.19 on 2023-06-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='profile_pic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Factory', 'Factory'), ('Customer', 'Customer')], default='Customer', max_length=20),
        ),
    ]
