# Generated by Django 4.1.7 on 2023-03-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dic_price',
            field=models.IntegerField(default=0, blank=True, null=True)
        ),
    ]
