# Generated by Django 3.2.19 on 2023-06-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0002_remove_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
    ]
