# Generated by Django 3.2.19 on 2023-06-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0003_remove_subcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='products')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_mul_ing', to='Shop_app.product')),
            ],
        ),
    ]
