# Generated by Django 4.1.7 on 2023-03-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0003_alter_product_dic_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='Category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shop_app.category'),
            preserve_default=False,
        ),
    ]
