# Generated by Django 3.2.19 on 2023-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0004_productmoreimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
