# Generated by Django 4.1.7 on 2023-05-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0004_subcategory_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='Category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='Shop_app.category'),
        ),
    ]
