# Generated by Django 3.2.19 on 2023-06-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0005_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quintity',
            field=models.IntegerField(default=0),
        ),
    ]
