# Generated by Django 4.2.9 on 2024-02-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0005_remove_product_product_meterials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=1, max_length=260),
            preserve_default=False,
        ),
    ]
