# Generated by Django 4.2.9 on 2024-02-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0006_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='wood_details',
            new_name='Meterials_details',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Width',
            new_name='deepth',
        ),
        migrations.AlterField(
            model_name='product',
            name='fabrics_details',
            field=models.CharField(blank=True, max_length=165, null=True),
        ),
    ]
