# Generated by Django 4.1.7 on 2023-05-25 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0006_category_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shop_app.main_category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_cat', to='Shop_app.main_category'),
        ),
    ]
