# Generated by Django 3.2.19 on 2023-06-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0006_product_product_quintity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='product_meterials',
        ),
        migrations.AddField(
            model_name='product',
            name='Width',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='lenth',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
