# Generated by Django 4.2.9 on 2024-03-01 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop_app', '0007_rename_wood_details_product_meterials_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewMsg', models.TextField()),
                ('rating', models.IntegerField(default=4)),
                ('reviewStatus', models.BooleanField(default=False)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop_app.product')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
