# Generated by Django 4.2.9 on 2024-03-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0008_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='ClientName',
            field=models.CharField(default=1, max_length=156),
            preserve_default=False,
        ),
    ]
