# Generated by Django 4.1.4 on 2024-05-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0009_productreview_clientname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_video_id',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_pic',
            field=models.ImageField(default=1, upload_to='products'),
            preserve_default=False,
        ),
    ]
